### ISSUE TITLE
Horarios #1

### ISSUE THREAD

**Issue by Zxmoophv** [liederivative/ponchador-tesis-loyola#10]
En editar horarios los campos viene con valor null y activos, lo que provoca que cuando intento guardar explote.

**Comment by liederivative** [comment]
Favor agregar imagenes o codigo de error. No se reproduce en mi ambiente.

**Comment by Zxmoophv** [comment]
![image](https://user-images.githubusercontent.com/29081340/27998438-71e0d5c2-64e5-11e7-9581-84fe9cfcec6b.png)

La situación solo sucede en la universidades y no en el ministerio. Pues, creas una universidad, accedes, creas un horario y vas a editar. Ahí se encuentra la situación.
