### ISSUE TITLE
Consola #2

### ISSUE THREAD

**Issue by Zxmoophv** [liederivative/ponchador-tesis-loyola#18]
Deberíamos evitar que no existan usuarios sin privilegios para acceder a consola. Así cuando por error alguien intente borrar el rol del root no le será permitido. Ya que es un problema que que todos los admin pierdan acceso por ese error de uno de ellos.

**Comment by liederivative** [comment]
En la mescyt no pasa. En la universidad no pueden borrar ROOT, y le agrege que no borren el role Admin.
